#更多规则使用说明请参考 http://AppOpt.suto.top

# 网易云后台播放子进程绑定到CPU0,1,5,6
# com.netease.cloudmusic:play=0-1,5-6

# 抖音主线程绑定到中大核
# com.ss.android.ugc.aweme{RenderThread}=6-7

# 支付宝渲染线程在识别到应用100秒后绑定到中大核（1000 × 100毫秒）
# com.eg.android.AlipayGphone{RenderThread}:1000=2-6

# 注意！上述3条规则仅作为用法参考实例
# 后续添加的规则请不要以#或//开头（这两种整行注释不会生效）
